### ISSUE TITLE
Establish a directory structure

### ISSUE THREAD

**Issue by youngant** [adam-broussard/bestreads#10]
We should decide on how to organize the files. I'd propose the following directories for now:
```
src/
data/
notebooks/
figures/
```

**Comment by youngant** [comment]
We should decide on how to organize the files. I'd propose the following directories for now:
```
src/
data/
notebooks/
figures/
```

**Comment by adam-broussard** [comment]
Check out the [datasummary](https://github.com/adam-broussard/bestreads/tree/datasummary) branch.  If we use `pip install -e .` to install the package, we can make changes to files that will be immediately reflected in the installation.  It's a bit similar to your suggestion.  Having the `notebooks/` folder where you've indicated here also allows us to access all the functions in the source files from the notebooks without Python getting confused that the notebook folder is a module of `bestreads`, which is good.

I think we don't need to include a `data/` directory because empty folders aren't tracked by Git and I don't think we want it to track any files in there because they'll be pretty large.  Functionally, I think the (invisible) `data/` and (not invisible) `figures/` directories will make sense to sit in the `notebooks/` directory because they go with the example notebooks.  Does that sound reasonable?
